[package]
name = "zccache-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
description = "Core shared types and utilities for zccache"
publish = false

[dependencies]
crash-handler = "0.6"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
zccache-platform = { workspace = true }

[dev-dependencies]
dashmap = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
