[package]
name = "zccache-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
description = "Compiler detection and invocation parsing for zccache"
publish = false

[features]
default = ["native"]
native = ["dep:clang", "dep:serde_json", "dep:thiserror", "dep:zccache-core", "dep:zccache-hash", "dep:zccache-platform"]

[dependencies]
typed-path = { version = "=0.12.3", default-features = false }
clang = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
zccache-core = { workspace = true, optional = true }
zccache-hash = { workspace = true, optional = true }
zccache-platform = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
