[package]
name = "zccache-fingerprint"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
description = "Fingerprint engine and PyO3 extension module for zccache"
publish = false

[lib]
crate-type = ["rlib"]

[features]
default = []

[dependencies]
zccache-core = { workspace = true }
zccache-hash = { workspace = true }
fs2 = { workspace = true }
globset = "0.4"
jwalk = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
filetime = { workspace = true }
tempfile = { workspace = true }

[build-dependencies]

[lints]
workspace = true
