[package]
name = "zccache-watcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
description = "Cross-platform file watcher engine for zccache"
publish = false

[lib]
crate-type = ["rlib"]

[features]
default = []

[dependencies]
zccache-core = { workspace = true }
zccache-fscache = { workspace = true }
globset = "0.4"
jwalk = { workspace = true }
notify = { workspace = true }
rayon = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
